WebServer:
  Port: 8080
  ReadTimeout: 40
  WriteTimeout: 40
Database:
  Host: localhost
  Port: 3306
  User: root
  Pass: 031716cqp0222
  DBName: goodvs
EmailService:
  Host: smtp.qq.com
  Port: 25
  From: 826733088@qq.com
  Pass: ofzjlifjolcybcbb
