WebServer:
  Port: 8080
  ReadTimeout: 40
  WriteTimeout: 40
Database:
  Host: localhost
  Port: 3306
  User: root
  Pass: 031716cqp0222
  DBName: goodvs
EmailServer:
  Host: smtp.gmail.com
  Port: 587
  User:
